// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.pupol.beans.image;

import es.pupol.beans.image.ImageBean;

privileged aspect ImageBean_Roo_JavaBean {
    
    public String ImageBean.getUrl() {
        return this.url;
    }
    
    public void ImageBean.setUrl(String url) {
        this.url = url;
    }
    
}
