// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.pupol.beans.mail;

import es.pupol.beans.mail.MailBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MailBean_Roo_Configurable {
    
    declare @type: MailBean: @Configurable;
    
}
