// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.pupol.beans.mail;

import es.pupol.beans.mail.MailBean;

privileged aspect MailBean_Roo_JavaBean {
    
    public String MailBean.getEmail() {
        return this.email;
    }
    
    public void MailBean.setEmail(String email) {
        this.email = email;
    }
    
}
