// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.pupol.beans.phone;

import es.pupol.beans.phone.PhoneBean;

privileged aspect PhoneBean_Roo_JavaBean {
    
    public String PhoneBean.getPhone() {
        return this.phone;
    }
    
    public void PhoneBean.setPhone(String phone) {
        this.phone = phone;
    }
    
}
