// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.pupol.beans.center;

import es.pupol.beans.center.CenterBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CenterBean_Roo_Configurable {
    
    declare @type: CenterBean: @Configurable;
    
}
