// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.pupol.beans.mensaje;

import es.pupol.beans.mensaje.MensajeBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MensajeBean_Roo_Configurable {
    
    declare @type: MensajeBean: @Configurable;
    
}
